import{mkdirSync as x}from"node:fs";import{homedir as b}from"node:os";import{dirname as y,join as v}from"node:path";import{randomUUID as C}from"node:crypto";import{DatabaseSync as S}from"node:sqlite";function A(r=process.env){return r.LANGUAGE_COACH_DB_PATH||v(b(),".language-coach","language-coach.sqlite")}function L(){return new Date().toISOString()}function E(r,e){if(typeof r!="string")return e;try{return JSON.parse(r)}catch{return e}}function f(r){return{id:r.id,turnId:r.turn_id??void 0,inputLanguage:r.input_language||"other",originalExpression:r.original_expression,polishedExpression:r.polished_expression,corrections:E(r.corrections_json,[]),patterns:E(r.patterns_json,[]),examples:E(r.examples_json,[]),nativeLanguage:r.native_language,targetLanguage:r.target_language,createdAt:r.created_at}}var l=class{database;constructor(e=A()){x(y(e),{recursive:!0}),this.database=new S(e),this.database.exec("PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON;"),this.migrate()}migrate(){this.database.exec(`
      CREATE TABLE IF NOT EXISTS profile (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        native_language TEXT NOT NULL,
        target_language TEXT NOT NULL,
        coach_enabled INTEGER NOT NULL DEFAULT 1,
        updated_at TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS learning_notes (
        id TEXT PRIMARY KEY,
        turn_id TEXT UNIQUE,
        input_language TEXT NOT NULL DEFAULT 'other' CHECK (input_language IN ('native', 'target', 'mixed', 'other')),
        original_expression TEXT NOT NULL,
        polished_expression TEXT NOT NULL,
        corrections_json TEXT NOT NULL,
        patterns_json TEXT NOT NULL,
        examples_json TEXT NOT NULL,
        native_language TEXT NOT NULL,
        target_language TEXT NOT NULL,
        created_at TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_learning_notes_created_at
        ON learning_notes(created_at DESC);
    `),this.database.prepare("PRAGMA table_info(learning_notes)").all().some(t=>t.name==="input_language")||this.database.exec("ALTER TABLE learning_notes ADD COLUMN input_language TEXT NOT NULL DEFAULT 'other'");let o=L();this.database.prepare(`INSERT OR IGNORE INTO profile
        (id, native_language, target_language, coach_enabled, updated_at)
        VALUES (1, 'Chinese', 'English', 1, ?)`).run(o)}getProfile(){let e=this.database.prepare("SELECT * FROM profile WHERE id = 1").get();return{nativeLanguage:e.native_language,targetLanguage:e.target_language,coachEnabled:!!e.coach_enabled,updatedAt:e.updated_at}}updateProfile(e){let o=this.getProfile(),t={nativeLanguage:e.nativeLanguage?.trim()||o.nativeLanguage,targetLanguage:e.targetLanguage?.trim()||o.targetLanguage,coachEnabled:e.coachEnabled??o.coachEnabled,updatedAt:L()};return this.database.prepare("UPDATE profile SET native_language = ?, target_language = ?, coach_enabled = ?, updated_at = ? WHERE id = 1").run(t.nativeLanguage,t.targetLanguage,t.coachEnabled?1:0,t.updatedAt),t}saveNote(e){let o=this.getProfile(),t={...e,id:C(),inputLanguage:e.inputLanguage||"other",originalExpression:e.originalExpression.trim(),polishedExpression:e.polishedExpression.trim(),nativeLanguage:e.nativeLanguage?.trim()||o.nativeLanguage,targetLanguage:e.targetLanguage?.trim()||o.targetLanguage,createdAt:L()};if(!t.originalExpression||!t.polishedExpression)throw new Error("Both originalExpression and polishedExpression are required.");let i=e.turnId?this.database.prepare("SELECT id FROM learning_notes WHERE turn_id = ?").get(e.turnId):void 0;if(i){let c=this.database.prepare("SELECT * FROM learning_notes WHERE id = ?").get(i.id);return f(c)}return this.database.prepare(`INSERT INTO learning_notes (
        id, turn_id, input_language, original_expression, polished_expression, corrections_json,
        patterns_json, examples_json, native_language, target_language, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(t.id,t.turnId??null,t.inputLanguage,t.originalExpression,t.polishedExpression,JSON.stringify(t.corrections),JSON.stringify(t.patterns),JSON.stringify(t.examples),t.nativeLanguage,t.targetLanguage,t.createdAt),t}hasNoteForTurn(e){return!!this.database.prepare("SELECT 1 FROM learning_notes WHERE turn_id = ?").get(e)}listNotes(e=100){let o=Math.max(1,Math.min(500,Math.trunc(e)));return this.database.prepare("SELECT * FROM learning_notes ORDER BY created_at DESC LIMIT ?").all(o).map(f)}deleteNote(e){return this.database.prepare("DELETE FROM learning_notes WHERE id = ?").run(e).changes>0}getProgress(){let e=this.listNotes(500),o=new Date,t=a=>a.toISOString().slice(0,10),i=new Map;for(let a of e){let n=a.createdAt.slice(0,10);i.set(n,(i.get(n)??0)+1)}let c=Array.from({length:7},(a,n)=>{let g=new Date(o);g.setUTCHours(0,0,0,0),g.setUTCDate(g.getUTCDate()-(6-n));let u=t(g);return{date:u,count:i.get(u)??0}}),_=0;for(let a=0;a<366;a+=1){let n=new Date(o);if(n.setUTCDate(n.getUTCDate()-a),(i.get(t(n))??0)>0)_+=1;else if(a>0||i.size>0)break}let p=new Map,d=new Map,s={native:0,target:0,mixed:0,other:0};for(let a of e){s[a.inputLanguage]+=1;for(let n of a.corrections)p.set(n.category,(p.get(n.category)??0)+1);for(let n of a.patterns){let g=n.pattern.trim().toLocaleLowerCase(),u=d.get(g)??{explanation:n.explanation,count:0};u.count+=1,d.set(g,u)}}return{totalNotes:e.length,notesThisWeek:c.reduce((a,n)=>a+n.count,0),activeDays:i.size,currentStreak:_,weeklyActivity:c,categoryCounts:[...p.entries()].map(([a,n])=>({category:a,count:n})).sort((a,n)=>n.count-a.count),recurringPatterns:[...d.entries()].map(([a,n])=>({pattern:a,...n})).sort((a,n)=>n.count-a.count).slice(0,8),languageUse:{...s,targetShare:s.native+s.target>0?Math.round(s.target/(s.native+s.target)*100):0}}}getDashboardData(e=100){return{profile:this.getProfile(),notes:this.listNotes(e),progress:this.getProgress()}}close(){this.database.close()}};async function N(){let r="";for await(let e of process.stdin)r+=e;return r?JSON.parse(r):{}}var m=await N(),h=new l,I=h.getProfile(),T=typeof m.turn_id=="string"?m.turn_id:"",O=T?h.hasNoteForTurn(T):!0;h.close();!I.coachEnabled||O||m.stop_hook_active?process.stdout.write(JSON.stringify({continue:!0})):process.stdout.write(JSON.stringify({decision:"block",reason:`Before finishing, decide whether turn ${T} has meaningful language-learning value. Save a note with the Language Coach MCP tool save_learning_note only if the user's expression contains a meaningful error, unnatural or contextually inappropriate wording, or a genuinely useful reusable pattern. Do not save a note if the expression is already natural, correct, and appropriate, or if the rewrite is merely an optional stylistic preference. Never save unrelated task content. Then return the response without discussing this internal decision.`}));
